# Configuration for:
#   (a) Processing of ROOT trees into histograms
#   (b) Analysis of histograms into final result
#
# The observables are structured into observable blocks (e.g. theta_g, subjet_z, etc.)
# each containing multiple individual subconfigurations (e.g. zcut, beta, subjetR, etc.),
# where each subconfiguration corresponds to a single unfolded result.
# One can also specify a list of jetR, which will be looped over.
#
# The process step is intended to loop over all observables simultaneously
# The analysis step is intended to run for a single observable block

process_observables: ['theta_g', 'zg']
jetR: [0.4]
jet_matching_distance: 0.6        # Match jets with deltaR < jet_matching_distance*jetR
reject_tracks_fraction: 0.0
eta_max: 0.9
debug_level: 0
dry_run: False
fast_simulation: False
#reclustering_algorithm: 'AKT'


# Observable block
theta_g:

  common_settings:
    xtitle: '#it{#theta}_{g}'
    ytitle: '#frac{1}{#it{#sigma}_{jet, inc}} #frac{d#it{#sigma}}{d#it{#theta}_{g}}'
    pt_bins_reported: [60, 80]
    max_reg_param: 10
    plot_overlay_list:
      - ['config1', 'config2', 'config3']
      - ['config4', 'config5', 'config6']
      
  # RM binnings from processing:
  #   pt-truth: 10 GeV
  #   pt-det: 5 GeV
  #   theta_g-truth: 0.01
  #   theta_g-det: 0.01

  config1:
    SoftDrop:
      zcut: 0.1
      beta: 0
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 150, 300]
    pt_bins_det: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80]
    pt_bins_det_sys_truncation: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 85]
    obs_bins_truth: [0., 0.1, 0.17, 0.23, 0.3, 0.4, 0.5, 0.6, 0.8, 1.0]
    obs_bins_det: [0., 0.1, 0.15, 0.2, 0.25, 0.3, 0.4, 0.5, 0.6, 0.8, 1.0]
    obs_bins_det_sys_binning: [0., 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.8, 0.9, 1.0]

  config2:
    SoftDrop:
      zcut: 0.1
      beta: 1
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 150, 300]
    pt_bins_det: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80]
    pt_bins_det_sys_truncation: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 85]
    obs_bins_truth: [0., 0.15, 0.25, 0.32, 0.4, 0.5, 0.6, 0.7, 0.8, 1.0]
    obs_bins_det: [0., 0.15, 0.25, 0.3, 0.35, 0.4, 0.5, 0.6, 0.7, 0.8, 1.0]
    obs_bins_det_sys_binning: [0., 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.9, 1.0]

  config3:
    SoftDrop:
      zcut: 0.1
      beta: 2
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 150, 300]
    pt_bins_det: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80]
    pt_bins_det_sys_truncation: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 85]
    obs_bins_truth: [0., 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 1.0]
    obs_bins_det: [0., 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 1.0]
    obs_bins_det_sys_binning: [0., 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.9, 1.0]
  
  config4:
    DynamicalGrooming:
      a: 0.1
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 150, 300]
    pt_bins_det: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80]
    pt_bins_det_sys_truncation: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 85]
    obs_bins_truth: [0., 0.07, 0.12, 0.17, 0.23, 0.3, 0.4, 0.6, 1.]
    obs_bins_det: [0., 0.07, 0.11, 0.15, 0.2, 0.25, 0.3, 0.4, 0.6, 1.]
    obs_bins_det_sys_binning: [0., 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.8, 0.9, 1.0]
      
  config5:
    DynamicalGrooming:
      a: 1.0
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 150, 300]
    pt_bins_det: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80]
    pt_bins_det_sys_truncation: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 85]
    obs_bins_truth: [0., 0.15, 0.25, 0.35, 0.45, 0.55, 0.65, 0.75, 0.85, 1.]
    obs_bins_det: [0., 0.15, 0.25, 0.35, 0.45, 0.55, 0.65, 0.75, 0.85, 1.]
    obs_bins_det_sys_binning: [0., 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.8, 0.9, 1.0]

  config6:
    DynamicalGrooming:
      a: 2.0
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 150, 300]
    pt_bins_det: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80]
    pt_bins_det_sys_truncation: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 85]
    obs_bins_truth: [0., 0.3, 0.4, 0.5, 0.6, 0.68, 0.75, 0.82, 0.9, 1.]
    obs_bins_det: [0., 0.3, 0.45, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.9, 1.]
    obs_bins_det_sys_binning: [0., 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.8, 0.9, 1.0]

# Observable block
zg:

  common_settings:
    xtitle: '#it{z}_{g}'
    ytitle: '#frac{1}{#it{#sigma}_{jet, inc}} #frac{d#it{#sigma}}{d#it{z}_{g}}'
    pt_bins_reported: [60, 80]
    max_reg_param: 10
    plot_overlay_list:
      - ['config1', 'config2', 'config3']
      - ['config4', 'config5', 'config6']
      
  # RM binnings from processing:
  #   pt-truth: 10 GeV
  #   pt-det: 5 GeV
  #   z-truth: 0.01
  #   z-det: 0.01

  config1:
    SoftDrop:
      zcut: 0.1
      beta: 0
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 150, 300]
    pt_bins_det: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80]
    pt_bins_det_sys_truncation: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 85]
    obs_bins_truth: [0.1, 0.13, 0.16, 0.2, 0.25, 0.3, 0.35, 0.4, 0.5]
    obs_bins_det: [0.1, 0.13, 0.16, 0.2, 0.25, 0.3, 0.35, 0.4, 0.5]
    obs_bins_det_sys_binning: [0.1, 0.12, 0.14, 0.16, 0.18, 0.2, 0.22, 0.25, 0.28, 0.31, 0.34, 0.37, 0.4, 0.43, 0.46, 0.5]

  config2:
    SoftDrop:
      zcut: 0.1
      beta: 1
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 150, 300]
    pt_bins_det: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80]
    pt_bins_det_sys_truncation: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 85]
    obs_bins_truth: [0., 0.05, 0.08, 0.11, 0.15, 0.2, 0.25, 0.3, 0.4, 0.5]
    obs_bins_det: [0., 0.05, 0.08, 0.11, 0.15, 0.2, 0.25, 0.3, 0.4, 0.5]
    obs_bins_det_sys_binning: [0., 0.04, 0.07, 0.1, 0.12, 0.14, 0.16, 0.18, 0.2, 0.22, 0.25, 0.28, 0.31, 0.34, 0.37, 0.4, 0.43,   0.46, 0.5]

  config3:
    SoftDrop:
      zcut: 0.1
      beta: 2
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 150, 300]
    pt_bins_det: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80]
    pt_bins_det_sys_truncation: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 85]
    obs_bins_truth: [0., 0.05, 0.08, 0.11, 0.15, 0.2, 0.25, 0.3, 0.4, 0.5]
    obs_bins_det: [0., 0.05, 0.08, 0.11, 0.15, 0.2, 0.25, 0.3, 0.4, 0.5]
    obs_bins_det_sys_binning: [0., 0.04, 0.07, 0.1, 0.12, 0.14, 0.16, 0.18, 0.2, 0.22, 0.25, 0.28, 0.31, 0.34, 0.37, 0.4, 0.43,   0.46, 0.5]
      
  config4:
    DynamicalGrooming:
      a: 0.1
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 150, 300]
    pt_bins_det: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80]
    pt_bins_det_sys_truncation: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 85]
    obs_bins_truth: [0., 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5]
    obs_bins_det: [0., 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5]
    obs_bins_det_sys_binning: [0., 0.05, 0.1, 0.12, 0.14, 0.16, 0.18, 0.2, 0.22, 0.25, 0.28, 0.31, 0.34, 0.37, 0.4, 0.43, 0.46, 0.5]
      
  config5:
    DynamicalGrooming:
      a: 1.0
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 150, 300]
    pt_bins_det: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80]
    pt_bins_det_sys_truncation: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 85]
    obs_bins_truth: [0., 0.05, 0.09, 0.12, 0.15, 0.2, 0.25, 0.3, 0.4, 0.5]
    obs_bins_det: [0., 0.05, 0.09, 0.12, 0.15, 0.2, 0.25, 0.3, 0.4, 0.5]
    obs_bins_det_sys_binning: [0., 0.05, 0.1, 0.12, 0.14, 0.16, 0.18, 0.2, 0.22, 0.25, 0.28, 0.31, 0.34, 0.37, 0.4, 0.43, 0.46, 0.5]
      
  config6:
    DynamicalGrooming:
      a: 2.0
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 150, 300]
    pt_bins_det: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80]
    pt_bins_det_sys_truncation: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 85]
    obs_bins_truth: [0., 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.4, 0.5]
    obs_bins_det: [0., 0.03, 0.06, 0.1, 0.15, 0.2, 0.25, 0.3, 0.4, 0.5]
    obs_bins_det_sys_binning: [0., 0.05, 0.1, 0.12, 0.14, 0.16, 0.18, 0.2, 0.22, 0.25, 0.28, 0.31, 0.34, 0.37, 0.4, 0.43, 0.46, 0.5]


###############################################################################
# Theory comparison parameters
do_theory_comp: True
th_fold_observable: "theta_g"
#response_levels: [["p", "ch", "off"], ["p", "h", "off"], ["h", "ch", "on"]]
response_levels: [["p", "h", "off"]]
theory_pt_bins: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
                 85, 90, 95, 100, 105, 110, 115, 120, 125, 130, 135, 140, 145,
                 150, 155, 160, 165, 170, 175, 180, 185, 190, 195, 200]
final_pt_bins: [10, 20, 40, 60, 80, 100, 150, 200]
theory_obs_bins: [0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
                  0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
                  0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
                  0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
                  0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
                  0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
                  0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
                  0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
                  0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
                  0.99, 1.  ]
theory_dir: "/home/ezra/theory_predictions/theta_g/"
pt_scale_factors_path: "/home/ezra/theory_predictions/"
response_files: ["/rstorage/alice/AnalysisResults/theta_g/607481/AnalysisResultsFinal.root",
                 "/rstorage/alice/AnalysisResults/theta_g/607530/AnalysisResultsFinal.root"]
response_labels: ["PYTHIA8", "Herwig7"]
rebin_theory_response: False


###############################################################################
# Analysis parameters

file_format: '.pdf'
output_dir: '/Users/jamesmulligan/Analysis_theta_g_pp/roounfold_output/pp/343450'
roounfold_path: '/Users/jamesmulligan/heppy/external/roounfold/roounfold-current/lib/libRooUnfold.dylib'

analysis_observable: 'zg'
do_unfolding: False
force_rebin: True
do_systematics: True
do_plot_final_result: True
do_plot_performance: False
figure_approval_status: ''

# List of which systematics to perform
# Options: [main, trkeff, prior1, prior2, truncation, binning]
systematics_list:
  - main
  - trkeff
  - prior1
  - prior2
  - truncation
  - binning
  - fastsim_generator0
  - fastsim_generator1

# Paths to processing output, to be used for unfolding
main_data: '/Users/jamesmulligan/Analysis_theta_g_pp/AnalysisResults/LHC17pq/343450/AnalysisResultsFinal.root'
main_response: '/Users/jamesmulligan/Analysis_theta_g_pp/AnalysisResults/LHC18b8/343610/AnalysisResultsFinal.root'
trkeff_response: '/Users/jamesmulligan/Analysis_theta_g_pp/AnalysisResults/LHC18b8_trkeff/343612/AnalysisResultsFinal.root'
fastsim_response:
 - '/Users/jamesmulligan/Analysis_theta_g_pp/AnalysisResults/LHC18b8_fastsim_pythia/343613/AnalysisResultsFinal.root'
 - '/Users/jamesmulligan/Analysis_theta_g_pp/AnalysisResults/LHC18b8_fastsim_herwig/343614/AnalysisResultsFinal_excl3bins.root'

# Prior variation parameters
prior_variation_option: 1
prior1_variation_parameter: 0.5
prior2_variation_parameter: -0.5

# Theory comparisons
fPythia: '/Users/jamesmulligan/Analysis_theta_g/Pythia_new/pythia.root'

fNLL: ''
fNPcorrection_numerator: '/Users/jamesmulligan/Analysis_theta_g/NP_correction/Full_hadON_mpiON_isrON/default_output.root'
fNPcorrection_denominator: '/Users/jamesmulligan/Analysis_theta_g/NP_correction/Full_hadOFF_mpiOFF_isrOFF/default_output.root'
