# Processing parameters
jetR: [0.2]
alphas: [1, 1.5, 2, 3]

# For extra verbose output in some functions
debug_level: 0

process_observables: ['ang']
jet_matching_distance: 0.6        # Match jets with deltaR < jet_matching_distance*jetR

# Background subtraction parameters for Pb-Pb
constituent_subtractor:
  max_distance: [0.05, 0.1, 0.5]
  main_R_max: 0.1
  alpha: 0
  max_eta: 0.9
  bge_rho_grid_size: 1.0
  max_pt_correct: 100
  ghost_area: 0.01

# Max eta value (for plots)
eta_max: 0.9

###############################################################################
# Rebinning and unfolding parameters/configurations for angularity observables
ang:

  common_settings:
    xtitle: '#it{#lambda}_{#it{#alpha}}^{#it{#kappa}=1}'
    ytitle: '#frac{1}{#it{#sigma}_{jet}} #frac{d#it{#sigma}}{d#it{#lambda}_{#it{#alpha}}^{#it{#kappa}=1}}'
    pt_bins_reported: [40, 60]
    plot_overlay_list:
      - ['config_R0.2_1', 'config_R0.2_1.5', 'config_R0.2_2', 'config_R0.2_3']
      - ['config_R0.2_1_SD', 'config_R0.2_1.5_SD', 'config_R0.2_2_SD', 'config_R0.2_3_SD']
    max_reg_param: 20
    reg_param_variation: 2

  ############################################################################
  # Different R & alpha configurations
  config_R0.2_1:
    R: 0.2
    alpha: 1
    pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [40, 45, 50, 60, 70, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [45, 50, 60, 70, 80, 100, 120]
    obs_bins_truth: [0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.55, 0.75]
    obs_max_reported: [0.55]
    obs_bins_det: [0, 0.08, 0.12, 0.16, 0.20, 0.24, 0.28, 0.32, 0.36, 0.42, 0.55, 0.75]
    obs_bins_det_sys_binning: [0, 0.07, 0.11, 0.15, 0.19, 0.24, 0.29, 0.33, 0.37, 0.42, 0.54, 0.75]
    reg_param:
      0.2: 15

  config_R0.2_1.5:
    R: 0.2
    alpha: 1.5
    pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [40, 45, 50, 60, 70, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [45, 50, 60, 70, 80, 100, 120]
    obs_bins_truth: [0, 0.05, 0.08, 0.1, 0.14, 0.18, 0.2, 0.24, 0.3, 0.5, 0.7]
    obs_max_reported: [0.5]
    obs_bins_det: [0, 0.05, 0.08, 0.1, 0.12, 0.14, 0.16, 0.18, 0.20, 0.22, 0.26, 0.3, 0.5, 0.7]
    obs_bins_det_sys_binning: [0, 0.045, 0.075, 0.09, 0.11, 0.13, 0.15, 0.17, 0.19,
                               0.21, 0.25, 0.32, 0.5, 0.7]
    reg_param:
      0.2: 15

  config_R0.2_2:
    R: 0.2
    alpha: 2
    pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [40, 45, 50, 60, 70, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [45, 50, 60, 70, 80, 100, 120]
    obs_bins_truth: [0, 0.02, 0.04, 0.07, 0.1, 0.13, 0.16, 0.2, 0.3, 0.40, 0.7]
    obs_max_reported: [0.4]
    obs_bins_det: [0, 0.02, 0.04, 0.06, 0.08, 0.1, 0.12, 0.14, 0.18, 0.25, 0.40, 0.7]
    obs_bins_det_sys_binning: [0, 0.015, 0.045, 0.055, 0.065, 0.075, 0.085, 0.11, 0.13, 0.15,
                               0.17, 0.19, 0.21, 0.27, 0.40, 0.7]
    reg_param:
      0.2: 15

  config_R0.2_3:
    R: 0.2
    alpha: 3
    pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [40, 45, 50, 60, 70, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [45, 50, 60, 70, 80, 100, 120]
    obs_bins_truth: [0, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.08, 0.1, 0.15, 0.25, 0.35]
    obs_max_reported: [0.25]
    obs_bins_det: [0, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.09, 0.11, 0.14, 0.18, 0.25, 0.35]
    obs_bins_det_sys_binning: [0, 0.01, 0.025, 0.03, 0.04, 0.045, 0.055, 0.065,
                               0.095, 0.12, 0.15, 0.19, 0.25, 0.35]
    reg_param:
      0.2: 15

  ############################################################################
  # Different R & alpha configurations for SD
  config_R0.2_1_SD:
    SoftDrop:
      zcut: 0.2
      beta: 0
    R: 0.2
    alpha: 1
    pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [40, 45, 50, 60, 70, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [45, 50, 60, 70, 80, 100, 120]
    obs_bins_truth: [0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.4, 0.55, 0.7]
    obs_max_reported: [0.55]
    obs_bins_det: [0, 0.04, 0.08, 0.12, 0.15, 0.18, 0.21, 0.24, 0.27, 0.3, 0.38, 0.55, 0.7]
    obs_bins_det_sys_binning: [0, 0.05, 0.09, 0.13, 0.16, 0.19, 0.22, 0.25, 0.28, 0.31, 0.38, 0.56, 0.7]
    reg_param:
      0.2: 10

  config_R0.2_1.5_SD:
    SoftDrop:
      zcut: 0.2
      beta: 0
    R: 0.2
    alpha: 1.5
    pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [40, 45, 50, 60, 70, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [45, 50, 60, 70, 80, 100, 120]
    obs_bins_truth: [0, 0.02, 0.05, 0.08, 0.11, 0.15, 0.2, 0.3, 0.5, 0.7]
    obs_max_reported: [0.5]
    obs_bins_det: [0, 0.01, 0.02, 0.04, 0.06, 0.08, 0.1, 0.15, 0.2, 0.3, 0.5, 0.7]
    obs_bins_det_sys_binning: [0, 0.01, 0.025, 0.04, 0.065, 0.085, 0.11, 0.16, 0.21, 0.31, 0.48, 0.7]
    reg_param:
      0.2: 10

  config_R0.2_2_SD:
    SoftDrop:
      zcut: 0.2
      beta: 0
    R: 0.2
    alpha: 2
    pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [40, 45, 50, 60, 70, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [45, 50, 60, 70, 80, 100, 120]
    obs_bins_truth: [0, 0.02, 0.04, 0.07, 0.1, 0.13, 0.16, 0.25, 0.45, 0.65]
    obs_max_reported: [0.45]
    obs_bins_det: [0, 0.01, 0.02, 0.03, 0.05, 0.07, 0.1, 0.12, 0.15, 0.25, 0.4, 0.65]
    obs_bins_det_sys_binning: [0, 0.005, 0.015, 0.025, 0.035, 0.05, 0.075, 0.1, 
                                0.13, 0.16, 0.26, 0.45, 0.65]
    reg_param:
      0.2: 10

  config_R0.2_3_SD:
    SoftDrop:
      zcut: 0.2
      beta: 0
    R: 0.2
    alpha: 3
    pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [40, 45, 50, 60, 70, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [45, 50, 60, 70, 80, 100, 120]
    obs_bins_truth: [0, 0.005, 0.01, 0.02, 0.03, 0.05, 0.06, 0.08, 0.1, 0.15, 0.3, 0.5]
    obs_max_reported: [0.3]
    obs_bins_det: [0, 0.005, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.08, 0.1, 0.15, 0.3, 0.5]
    obs_bins_det_sys_binning: [0, 0.005, 0.01, 0.02, 0.03, 0.04, 0.06, 0.09, 0.11, 0.16, 0.32, 0.5]
    reg_param:
      0.2: 10


###############################################################################
# Analysis & plotting parameters
file_format: ".pdf"
output_dir: "/rstorage/alice/AnalysisResults/ang/PbPb/AngR02_ptbin2"
results_pp: "/rstorage/alice/AnalysisResults/ang/AngR02_ptbin2/ang/final_results/fFinalResults.root"
roounfold_path: "$HEPPY_DIR/external/roounfold/roounfold-current/lib/libRooUnfold.so"

analysis_observable: 'ang'
do_unfolding: True
force_rebin: False
do_systematics: True
do_plot_final_result: True
do_plot_performance: False
figure_approval_status: 'Work In Progress'

# Whether or not to use the previous measurement in ratio
use_prev_result: False

# List of which systematics to perform
# Options: [main, trkeff, prior1, prior2, truncation, binning, \
#           random_mass, fastsim_generator0, fastsim_generator1]
systematics_list:
  - main
  - trkeff
  - prior1
  - prior2
  - truncation
  - binning
  - random_mass
  - fastsim_generator0
  - fastsim_generator1
  - fastsim_generator2
  - fastsim_generator3
  - subtraction1
  - subtraction2
  - thermal_closure

# Paths to processing output, to be used for unfolding
main_data: '/rstorage/alice/AnalysisResults/ang/872257/AnalysisResultsFinal.root'
main_response: '/rstorage/alice/AnalysisResults/ang/877553/AnalysisResultsFinal.root'
trkeff_response: '/rstorage/alice/AnalysisResults/ang/879564/AnalysisResultsFinal.root'
randmass_data: '/rstorage/alice/AnalysisResults/ang/890497/AnalysisResultsFinal.root'
randmass_response: '/rstorage/alice/AnalysisResults/ang/879602/AnalysisResultsFinal.root'
# fastsim order: PYTHIA, Herwig, JEWEL (recoils off), JEWEL (recoils on)
fastsim_response: ['/rstorage/alice/AnalysisResults/ang/934788/AnalysisResultsFinal.root',
                   '/rstorage/alice/AnalysisResults/ang/987484/AnalysisResultsFinal.root',
                   '/rstorage/alice/AnalysisResults/ang/934787/AnalysisResultsFinal.root',
                   '/rstorage/alice/AnalysisResults/ang/997583/AnalysisResultsFinal.root']
thermal_closure: '/rstorage/alice/AnalysisResults/ang/950196/AnalysisResultsFinal.root'

# R_max variations
R_max_variation1: 0.05
R_max_variation2: 0.5

# Prior variation parameters
prior_variation_option: 1
prior1_variation_parameter: 0.5
prior2_variation_parameter: -0.5
