# Processing parameters
jetR: [0.2]

# For extra verbose output in some functions
debug_level: 0

process_observables: ['mass']
jet_matching_distance: 0.6        # Match jets with deltaR < jet_matching_distance*jetR

# Background subtraction parameters for Pb-Pb
constituent_subtractor:
  max_distance: [0.05, 0.1, 0.5]
  main_R_max: 0.1
  alpha: 0
  max_eta: 0.9
  bge_rho_grid_size: 1.0
  max_pt_correct: 100
  ghost_area: 0.01

# Max eta value (for plots)
eta_max: 0.9


###############################################################################
# Rebinning and unfolding parameters/configurations for jet mass observables
mass:

  common_settings:
    xtitle: '#it{m}_{jet} (GeV/#it{c}^{2})'
    ytitle: '#frac{1}{#it{#sigma}_{jet}} #frac{d#it{#sigma}}{d#it{m}_{jet}}'
    pt_bins_reported: [40, 60]
    plot_overlay_list:
      - ['config_m']
      - ['config_m_SD']
    max_reg_param: 15
    reg_param_variation: 1

  ############################################################################
  # Different alpha configurations
  config_m:
    name: "mass"
    R: 0.2
    pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [40, 45, 50, 60, 70, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [45, 50, 60, 70, 80, 100, 120]
    obs_bins_truth: [0, 1.2, 1.6, 2, 2.4, 2.8, 3.2, 3.6, 4, 4.4, 5, 5.6, 6.2, 7, 10]
    obs_max_reported: [7]
    obs_bins_det: [0, 1.2, 1.6, 2, 2.4, 2.8, 3.2, 3.6, 4, 4.4, 5, 5.6, 6.2, 7, 10]
    obs_bins_det_sys_binning: [0, 0.5, 1, 1.4, 1.8, 2.2, 2.6, 3, 3.4, 3.8, 4.2, 4.6, 5.2,
                               5.8, 6.8, 8, 9, 12]
    reg_param:
      0.2: 2

  ############################################################################
  # Different alpha configurations with SoftDrop
  config_m_SD:
    name: "groomed mass"
    R: 0.2
    pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [40, 45, 50, 60, 70, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [45, 50, 60, 70, 80, 100, 120]
    obs_bins_truth: [0, 0.3, 0.6, 0.9, 1.2, 1.6, 2, 2.4, 2.8, 3.2, 3.6, 4, 4.6, 5.2, 6, 7, 9]
    obs_max_reported: [7]
    obs_bins_det: [0, 0.3, 0.6, 0.9, 1.2, 1.6, 2, 2.4, 2.8, 3.2, 3.6, 4, 4.6, 5.2, 6, 7, 9]
    obs_bins_det_sys_binning: [0, 0.4, 0.7, 1, 1.4, 1.8, 2.2, 2.6, 3, 3.4, 3.8, 4.4, 5, 6, 7, 10]
    SoftDrop:
      zcut: 0.2
      beta: 0
    reg_param:
      0.2: 2


###############################################################################
# Analysis & plotting parameters
file_format: ".pdf"
output_dir: "/rstorage/alice/AnalysisResults/ang/PbPb/AngR02_ptbin2"
results_pp: "/rstorage/alice/AnalysisResults/ang/pp/AngR02_ptbin2/mass/final_results/fFinalResults.root"
roounfold_path: "$HEPPY_DIR/external/roounfold/roounfold-current/lib/libRooUnfold.so"

analysis_observable: 'mass'
do_unfolding: False
force_rebin: False
do_systematics: True
do_plot_final_result: True
do_plot_performance: False
figure_approval_status: 'Preliminary'

# Whether or not to use the previous measurement in ratio
use_prev_result: False

# List of which systematics to perform
# Options: [main, trkeff, prior1, prior2, truncation, binning, \
#           random_mass, fastsim_generator0, fastsim_generator1]
systematics_list:
  - main
  - trkeff
  - prior1
  - prior2
  - truncation
  - binning
  - random_mass
  - fastsim_generator0
  - fastsim_generator1
  - fastsim_generator2
#  - fastsim_generator3
  - subtraction1
  - subtraction2
  - thermal_closure

# Paths to processing output, to be used for unfolding
main_data: '/rstorage/alice/AnalysisResults/ang/1020932/AnalysisResultsFinal.root'
main_response: '/rstorage/alice/AnalysisResults/ang/1021096/Scaled_no_cuts/AnalysisResultsFinal_no1-4.root'
trkeff_response: '/rstorage/alice/AnalysisResults/ang/1150066/Scaled_no_cuts/AnalysisResultsFinal_no1-4.root'
randmass_data: '/rstorage/alice/AnalysisResults/ang/1028380/AnalysisResultsFinal.root'
randmass_response: '/rstorage/alice/AnalysisResults/ang/1028397/AnalysisResultsFinal_no1-4.root'
# fastsim order: PYTHIA, Herwig, JEWEL (recoils off), JEWEL (recoils on)
fastsim_response: ['/rstorage/alice/AnalysisResults/ang/1028398/AnalysisResultsFinal_no1-5.root',
                   '/rstorage/alice/AnalysisResults/ang/1028400/Scaled_no_cuts/AnalysisResultsFinal_no1-4.root',
                   '/rstorage/alice/AnalysisResults/ang/1028399/AnalysisResultsFinal_no1-4.root',
                   '/rstorage/alice/AnalysisResults/ang/997583/AnalysisResultsFinal.root']
thermal_closure: '/rstorage/alice/AnalysisResults/ang/1021094/AnalysisResultsFinal.root'

# Histograms for theory predictions
theory_predictions: ['/rstorage/alice/AnalysisResults/ang/1216098/Scaled_no_cuts/AnalysisResultsFinal_no1-4.root',
                     '/rstorage/alice/AnalysisResults/ang/1216355/Scaled_no_cuts/AnalysisResultsFinal_no1-4.root',
                     '/rstorage/alice/AnalysisResults/ang/1216018/Scaled_no_cuts/AnalysisResultsFinal_no1-4.root',
                     '/rstorage/jetscape/AnalysisResults/1223149/v3/AnalysisResultsFinal.root']
theory_predictions_names: ["JEWEL (recoils off)", "JEWEL (recoils on)", "JEWEL pp", "JETSCAPE (MATTER+LBT)"]
# R_max variations
R_max_variation1: 0.05
R_max_variation2: 0.5

# Prior variation parameters
prior_variation_option: 2
prior1_variation_parameter: 0.1
prior2_variation_parameter: -0.1

