# Configuration for:
#   (a) Processing of ROOT trees into histograms
#   (b) Analysis of histograms into final result
#
# The observables are structured into observable blocks (e.g. theta_g, subjet_z, etc.)
# each containing multiple individual subconfigurations (e.g. zcut, beta, subjetR, etc.),
# where each subconfiguration corresponds to a single unfolded result.
# One can also specify a list of jetR, which will be looped over.
#
# The process step is intended  to loop over all observables simultaneously
# The analysis step is intended to run for a single observable block

process_observables: ['leading_subjet_z']
jetR: [0.4]
jet_matching_distance: 0.6        # Match jets with deltaR < jet_matching_distance*jetR
mc_fraction_threshold: 0.5
reject_tracks_fraction: 0.02
eta_max: 0.9
debug_level: 0
dry_run: False
fast_simulation: True
jetscape: False
#event_number_max: 1000

constituent_subtractor:
  max_distance: [0.05, 0.25, 0.7]
  main_R_max: 0.25
  alpha: 0
  max_eta: 0.9
  bge_rho_grid_size: 1.0
  max_pt_correct: 100
  ghost_area: 0.01

emb_file_list: '/rstorage/alice/data/LHC18qr/570/files.txt'
#emb_file_list: '/Users/jamesmulligan/Analysis_theta_g/test/test_LHC18qr_pass3/PbPb_file_list.txt'

# Observable block
inclusive_subjet_z:

  common_settings:
    xtitle: '#it{z_{r}}'
    ytitle: '#frac{1}{#it{N}_{jets}} #frac{d#it{N}}{d#it{z_{r}}}'
    pt_bins_reported: [60, 80, 100]
    max_reg_param: 10
    plot_overlay_list:
      - ['config1', 'config2']
      
  # RM binnings from processing:
  #   pt-truth: 10 GeV
  #   pt-det: 5 GeV
  #   z-truth: 0.01
  #   z-det: 0.01

  config1:
    subjet_R: 0.1
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 120, 150, 300]
    pt_bins_det: [35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 120]
    pt_bins_det_sys_truncation: [30, 35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 120]
    obs_bins_truth: [0., 0.02, 0.04, 0.06, 0.1, 0.2, 0.34, 0.5, 0.66, 0.76, 0.82, 0.88, 0.94, 1.0]
    obs_bins_det: [0., 0.02, 0.04, 0.06, 0.1, 0.2, 0.34, 0.5, 0.66, 0.76, 0.82, 0.88, 0.94, 1.0]
    obs_bins_det_sys_binning: [0., 0.01, 0.02, 0.03, 0.04, 0.06, 0.12, 0.18, 0.24, 0.3, 0.36, 0.42, 0.48, 0.54, 0.6, 0.66, 0.72, 0.8, 0.9, 0.96, 0.98, 0.99, 1.0]
    
  config2:
    subjet_R: 0.2
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 120, 150, 300]
    pt_bins_det: [35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 120]
    pt_bins_det_sys_truncation: [30, 35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 120]
    obs_bins_truth: [0., 0.02, 0.04, 0.06, 0.1, 0.2, 0.34, 0.5, 0.66, 0.76, 0.82, 0.88, 0.94, 1.0]
    obs_bins_det: [0., 0.02, 0.04, 0.06, 0.1, 0.2, 0.34, 0.5, 0.66, 0.76, 0.82, 0.88, 0.94, 1.0]
    obs_bins_det_sys_binning: [0., 0.01, 0.02, 0.03, 0.04, 0.06, 0.12, 0.18, 0.24, 0.3, 0.36, 0.42, 0.48, 0.54, 0.6, 0.66, 0.72, 0.8, 0.9, 0.96, 0.98, 0.99, 1.0]

# Observable block
leading_subjet_z:

  common_settings:
    xtitle: '#it{z_{r}}'
    ytitle: '#frac{1}{#it{N}_{jets}} #frac{d#it{N}}{d#it{z_{r}}}'
    pt_bins_reported: [80, 120]
    max_reg_param: 10
    plot_overlay_list:
      - ['config1', 'config2']
      
  # RM binnings from processing:
  #   pt-truth: 10 GeV
  #   pt-det: 5 GeV
  #   z-truth: 0.01
  #   z-det: 0.01

  config1:
    subjet_R: 0.1
    pt_bins_truth: [10, 20, 40, 60, 80, 120, 150, 200]
    pt_bins_det: [70, 75, 80, 90, 100, 110, 120, 150]
    pt_bins_det_sys_truncation: [50, 55, 60, 65, 70, 75, 80, 90, 100, 120]
    obs_bins_truth: [0., 0.6, 0.7, 0.77, 0.83, 0.89, 0.95, 1.0]
    obs_bins_det: [0.5, 0.6, 0.7, 0.77, 0.83, 0.89, 0.95, 1.0]
    obs_bins_det_sys_binning: [0.6, 0.66, 0.72, 0.8, 0.9, 0.96, 0.98, 1.0]

  config2:
    subjet_R: 0.2
    pt_bins_truth: [10, 20, 40, 60, 80, 120, 150, 200]
    pt_bins_det: [60, 65, 70, 75, 80, 90, 100, 110, 120, 150]
    pt_bins_det_sys_truncation: [50, 55, 60, 65, 70, 75, 80, 90, 100, 120]
    obs_bins_truth: [0., 0.7, 0.8, 0.86, 0.9, 0.94, 0.98, 1.0]
    obs_bins_det: [0.5, 0.7, 0.8, 0.86, 0.9, 0.94, 0.98, 1.0]
    obs_bins_det_sys_binning: [0.6, 0.66, 0.72, 0.8, 0.9, 0.96, 0.98, 1.0]

###############################################################################
# Analysis parameters

file_format: '.pdf'
output_dir: '/Users/jamesmulligan/Analysis_subjet_z/output_analysis/PbPb/493675-04-jewel'
roounfold_path: '/Users/jamesmulligan/RooUnfold/build/libRooUnfold.dylib'

analysis_observable: 'leading_subjet_z'
do_unfolding: True
force_rebin: True
do_systematics: True
do_plot_final_result: True
do_plot_performance: False
figure_approval_status: 'Preliminary'

# List of which systematics to perform
systematics_list:
  - main
  - trkeff
  - prior1
  - prior2
  - truncation
  - binning
  - subtraction1
  - subtraction2
  - thermal_closure
  - fastsim_generator0
  - fastsim_generator1
  
# Prior variation parameters
prior_variation_option: 4
prior1_variation_parameter: 0.5
prior2_variation_parameter: -0.5

# R_max variations
R_max_variation1: 0.05
R_max_variation2: 0.7

# Paths to processing output, to be used for unfolding
main_data: '/Users/jamesmulligan/Analysis_subjet_z/output_process/LHC18qr/493675/AnalysisResultsFinal.root'
main_response: '/Users/jamesmulligan/Analysis_subjet_z/output_process/LHC20g4_embedding/493586/AnalysisResultsFinal.root'
trkeff_response: '/Users/jamesmulligan/Analysis_subjet_z/output_process/LHC20g4_embedding_trkeff/493682/AnalysisResultsFinal.root'

# Model uncertainty from fastsim (compare JEWEL fastsim to PYTHIA)
fastsim_response:
- '/Users/jamesmulligan/Analysis_theta_g/AnalysisResults/LHC20g4_embedding/336239/AnalysisResultsFinal.root'
- '/Users/jamesmulligan/Analysis_theta_g/AnalysisResults/LHC19f4_fastsim_jetscape/295402/AnalysisResultsFinal.root'

# Thermal closure test
thermal_closure: '/Users/jamesmulligan/Analysis_subjet_z/output_process/LHC20g4_thermal02/493676/AnalysisResultsFinal.root'
